name: wanted;bytheking
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Wanted; By The King
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f9f9f8'
    - '#42413e'
    - '#6b6b69'
    - '#cfcfcf'
  brandStrength: 0.5
  lightness: 0.6381540719885379
  saturation: 0.875
  rhythmicContrast: 0.5110929398797452
purpose: []
