name: wanted;bytheking
favicon: null
layout_spectrum: 0.5347302455920726
typography_spectrum: 0.2240961550269276
title: Wanted; By The King
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.500205964082852
  lightness: 0.6381540719885379
  saturation: 0.03758157277479768
  rhythmicContrast: 0.5110929398797452
purpose: []
